name: Deploy to EC2 via Bastion

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key for Bastion
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

    - name: SSH into Private EC2 via Bastion and Deploy
      run: |
        ssh -o ProxyCommand="ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -W %h:%p ${{ secrets.SSH_USER }}@${{ secrets.BASTION_HOST }}" \
            -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.PRIVATE_EC2_IP }} << 'EOF'
              set -e
              if [ ! -d "/home/ec2-user/accesshopetest1" ]; then
                git clone https://github.com/metniltest/accesshopetest2.git
              fi
              cd /home/ec2-user/accesshopetest1
              git pull origin main
              echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
              docker compose down
              docker compose up --build -d
        EOF

